apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-processing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-processing-service
  template:
    metadata:
      labels:
        app: message-processing-service
    spec:
      containers:
      - name: message-processing-service
        image: anurag2911/msgprocessorsvc:2.0
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "64Mi" # Minimum memory allocated to the container
            cpu: "100m" # Equivalent to 0.10 of a CPU core
          limits:
            memory: "128Mi" # Maximum memory the container can use
            cpu: "200m" # Equivalent to 0.2 of a CPU core
