apiVersion: v1
kind: Service
metadata:
  name: message-processing-service
spec:
  type: ClusterIP
  selector:
    app: message-processing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
